config:
    version: 1

classes:
    9A:
        Monday:
            1: "Английский Язык"
            2: "Русский Язык"
            3: "Физика"
            4: "История"
            5: "Алгебра"
            6: "Химия"
            7: "Биология"
