config:
    version: 1
    author: John Doe
    no-warnings: false
    logpath: ./log/
    # Если вы хотите, чтобы
    # логи отправлялись к вам
    # на почту, настройте это
    emaillogs:
        # По умолчанию протокол задан на SMTP,
        # но вы можете изменить на IMAP или POP3
        # protocol: SMTP
        ip: smtp.yandex.ru
        name: John Doe
        username: john.doe # john.doe@yandex.ru
        password: 1234
        ssl: true
        port: 465
        dest: me@gmail.com
    noposters: false
    noAutoBack: true
    configNotDone: true
    check_new_version: false


# posters:
#    1: poster-1.png
#    2: poster-2.png

# Сначала задайте учителей, потом уроки, потом классы.
# Если список с учителями слишком длинный, то его можно
# поместить в отдельный файл с названием, например, teachers.yml.
#
# ВАЖНО: Название должно содержать только латинские буквы / цифры и некоторые знаки пунктуации(., ,, -, _).
# Вы можете назвать файл как угодно, но это может вызвать нестабильность программы!
#
# Чтобы программа поняла, из какого файла загружать, напишите в списке
# teachers тег external: ПУТЬКФАЙЛУ
#
# Оно должно выглядеть так:
# teachers:
#     external: ПУТЬКФАЙЛУ
#     # Дальше программа не будет загружать!
#     # jd1 НЕ ПОЯВИТСЯ в списке!
#     jd1:
#         name: J. Doe
#         fullName: John Doe
#         cabinet: 5c
# Тег external работает со всеми другими списками, даже так:
#
# teachers:
#     jd1:
#         external: teacher-jd1.yml

teachers:
    at1:   [А. Т. Александровна, Антонова Татьяна Александровна, 6]
    vp1:   [В. П. Владимировна, Волкова Полина Владимировна, .]
    ga1:   [Г. А. Владимировна, Гориченко Анна Владимировна, 7]
    zt1:   [З. Т. Николаевна, Зенченко Татьяна Николаевна, н]
    zd1:   [З. Д. Александрович, Зинин Данил Александрович, н]
    ik1:   [И. К. Андреевна, Иващенко Карина Андреевна, .]
    ki1:   [К. И, Александровна, Казакова Ирина Александровна, .]
    ka1:   [К. А. Васильевна, Коварда Алёна Васильевна, н]
    ke1:   [К. Е. Николаевна, Козлова Елена Николаевна, .]
    kt1:   [К. Т. Борисовна, Крета Татьяна Борисовна, .]
    kt2:   [К. Т. Николаевна, Козлова Татьяна Николаевна, н]
    kg1:   [К. Г. Михайловна, Колосова Галина Михайловна, 18]
    la1:   [Л. А. Анатольевна, Ледина Алевтина Анатольевна, н]
    lt1:   [Л. Т. Анатольевна, Лимонова Татьяна Анатольевна, 4]
    mt1:   [М. Т. Сергеевна, Макарова Татьяна Сергеевна, н]
    mm1:   [М. М. Борисович, Моисеев Максим Борисович, 11]
    pl1:   [П. Л. Андреевна, Прециниек Людмила Андреевна, .]
    rv1:   [Р. В. Сергеевна, Рукасова Виолетта Сергеевна, н]
    sa1:   [С. А. Михайловна, Семёнова Александра Михайловна, 18]
    st1:   [С. Т. Геннадьевна, Семёнова Татьяна Геннадьевна, 8]
    tv1:   [Т. В. Владимировна, Ткаченко Владислава Владимировна, н]
    tl1:   [Т. Л. Дмитриевна, Точеная Любовь Дмитриевна, 12]
    ft1:   [Ф. Т. Владимировна, Фёдорова Татьяна Владимировна, н]

    john:  [И. И. Иванович, Иван Иванов Иванович, -1]

lessons:
    chm1:  [vp1, Химия, 18] # 8-10
    inf:   [vp1, Информатика, 20] # 7-10
    indp:  [vp1, Инд. Проект, 17] # 10
    fuck:  [john, Факультатив, 12]

    chr:   [ki1, Черчение, 7] # 7

    his:   [lt1, История, 4] # 5-10
    soc:   [lt1, Обществознание, 4] # 5-10

    eco1:  [lt1, Экономика, 4] # 10

    crf1:  [vp1, Технология, 7] # 7а, 8а
    crf2:  [ke1, Технология, 21] # 5-6
    crf3:  [mm1, Технология, 9] # 5-7

    pa1:   [zt1, Физкультура, .] # 1а, 3б, 4б, 10а
    pa2:   [zd1, Физкультура, .] # 1б, 3б, 4-9
    pa3:   [rv1, Физкультура, .] # 2а/б

    slb:   [sa1, ОБЖ, 18]

    fiz1:  [vp1, Физика, 9] # 8
    fiz2:  [mm1, Физика, 9] # 7а/б, 9

    alg1:  [ga1, Алгебра, 5] # 8-10
    alg2:  [ki1, Алгебра, 7] # 7а/б

    geom1: [ga1, Геометрия, 5] # 8-10
    geom2: [ki1, Геометрия, 7] # 7а/б

    bio:   [sa1, Биология, 18] # 5-10

    mth1:  [ki1, Математика, 7] # 5а/б
    mth2:  [ga1, Математика, 5] # 6а/б

    geo1:  [kt1, География, 10] # 7а-10
    geo2:  [sa1, География, 18] # 5-6, 7б

    en1:   [ik1, Английский, 19/12] # 1-8
    en2:   [kg1, Английский язык, 12] # 2-6, 7, 9
    en3:   [tl1, Английский язык, 12] # 8 - 10

    mus1:  [sa1, Музыка, 18] # 5 - 7
    mus2:  [vp1, Музыка, 10] # 8

    nlit:  [pl1, Рус. Литература, 17]

    lit1:  [at1, Литература, 6] # 7а/б, 9
    lit2:  [pl1, Литература, 17] # 5а, 6а/б
    lit3:  [st1, Литература, 8] # 5-9

    nru1:  [pl1, Родн. Русский, 17] # 7а, 9
    nru2:  [st1, Родн. Русский, 8] # 10а

    ru1:   [st1, Русский язык, 6] # 5б
    ru2:   [at1, Русский язык, 6] # 5а, 7а/б, 9
    ru3:   [st1, Русский язык, 8] # 6а/б, 8, 10


    st1a:  [kt2, Нач. Школа, 1а] # 1А
    st1b:  [m11, Нач. Школа, 1б] # 1Б
    st2a:  [la1, Нач. Школа, 2а] # 2А
    st2b:  [ft1, Нач. Школа, 2б] # 2Б
    st3a:  [ft1, Нач. Школа, 3а] # 3А
    st3b:  [tv1, Нач. Школа, 3б] # 3Б
    st4a:  [ka1, Нач. Школа, 4а] # 4А
    st4b:  [la1, Нач. Школа, 4б] # 4Б

    drw1:  [john, ИЗО, 18] # 5а/б
    drw2:  [john, ИЗО, 7] # 6а/б, 7а

grades:
# starter school
    1A:
        name: 1А
        cabinet: 1А
        teacher: john # kt2
        schedule: [
            [st1a],
            [st1a],
            [st1a],
            [st1a],
            [st1a]
        ]
    1B:
        name: 1Б
        cabinet: 1Б
        teacher: john # m11
        schedule: [
            [st1b],
            [st1b],
            [st1b],
            [st1b],
            [st1b]
        ]
    2A:
        name: 2А
        cabinet: 2А
        teacher: john
        schedule: [
            [st2a],
            [st2a],
            [st2a],
            [st2a],
            [st2a]
        ]
    2B:
        name: 2Б
        cabinet: 2Б
        teacher: john
        schedule: [
            [st2b],
            [st2b],
            [st2b],
            [st2b],
            [st2b]
        ]
    3A:
        name: 3А
        cabinet: 3А
        teacher: john
        schedule: [
            [st3a],
            [st3a],
            [st3a],
            [st3a],
            [st3a]
        ]
    3B:
        name: 3Б
        cabinet: 3Б
        teacher: john
        schedule: [
            [st3b],
            [st3b],
            [st3b],
            [st3b],
            [st3b]
        ]
    4A:
        name: 4А
        cabinet: 4А
        teacher: john
        schedule: [
            [st4a],
            [st4a],
            [st4a],
            [st4a],
            [st4a]
        ]
    4B:
        name: 4Б
        cabinet: 4Б
        teacher: john
        schedule: [
            [st4b],
            [st4b],
            [st4b],
            [st4b],
            [st4b]
        ]
# end starting school

    5A:
        name: 5А
        cabinet: 5А
        teacher: john
        schedule: [
            [ru2, lit2, mth1, en1, geo2, his],
            [mth1, soc, ru2, lit2, crf2, crf2],
            [ru2, mth1, his, mus1, pa2],
            [ru2, bio, mth1, en1, nru1, pa2],
            [drw1, mth1, en1, lit2, ru2]
        ]
    5B:
        name: 5Б
        cabinet: 5Б
        teacher: john
        schedule: [
            [mth1, ru1, lit3, geo2, his, mus1],
            [crf2, crf2, mth1, ru1, soc],
            [nru1, en1, mth1, pa2, ru1],
            [ru1, lit3, his, mth1, bio, en1],
            [mth1, ru1, pa2, drw1, lit3]
        ]
    6A:
        name: 6А
        cabinet: 6А
        teacher: john
        schedule: [
            [lit2, mth2, his, ru3, ru3],
            [ru3, mth2, en1, pa2, soc, drw2],
            [ru3, lit2, en1, mth2, mus1, pa2],
            [nru1, mth2, bio, ru3, crf2, crf2],
            [ru1, geo1, his, mth2, lit2, en1]
        ]
    6B:
        name: 6Б
        cabinet: 6Б
        teacher: john
        schedule: [
            [ru3, en1, mth2, lit2, drw2],
            [mth2, ru3, ru3, soc, pa2, lit2],
            [en1, mth2, ru3, ru3, lit2, his],
            [crf2, crf2, mth2, bio, ru3, his],
            [geo1, en1, mth2, pa2, mus1, nru1]
        ]
    7A:
        name: 7А
        cabinet: 7А
        teacher: john
        schedule: [
            [fiz2, alg2, ru2, lit1, en2, pa2],
            [soc, geom2, geo1, ru2, bio, inf, en2],
            [his, ru2, bio, fiz2, alg2, mus1, fuck],
            [geo1, ru2, en2, geo1, drw2, crf1, crf1],
            [his, nru1, lit1, alg2, pa2]
        ]


    9A:
        name: 9A
        cabinet: 9
        teacher: john
        schedule: [
            [en3, ru1, fiz2, his, alg1, chm1, bio],
            [geo1, chm1, geom1, fiz2, nlit, bio, lit1],
            [fiz2, his, lit1, nru1, en3, alg1, pa2],
            [pa2, soc, geo1, ru2, lit1, geo1],
            [inf, en2, slb, ru2, chm1, alg1]
        ]


