config:
    version: 1
    author: John Doe
    no-warnings: false
    logpath: ./log/
    # Если вы хотите, чтобы
    # логи отправлялись к вам
    # на почту, настройте это
    emaillogs:
        # По умолчанию протокол задан на SMTP,
        # но вы можете изменить на IMAP или POP3
        # protocol: SMTP
        ip: smtp.yandex.ru
        name: John Doe
        username: john.doe # john.doe@yandex.ru
        password: 1234
        ssl: true
        port: 465
    # noposters: true

# posters:
#    1: poster-1.png
#    2: poster-2.png

# Сначала задайте учителей, потом уроки, потом классы.
# Если список с учителями слишком длинный, то его можно
# поместить в отдельный файл с названием, например, teachers.yml.
#
# ВАЖНО: Название должно содержать только латинские буквы / цифры и некоторые знаки пунктуации(., ,, -, _).
# Вы можете назвать файл как угодно, но это может вызвать нестабильность программы!
#
# Чтобы программа поняла, из какого файла загружать, напишите в списке
# teachers тег external: ПУТЬКФАЙЛУ
#
# Оно должно выглядеть так:
# teachers:
#     external: ПУТЬКФАЙЛУ
#     # Дальше программа не будет загружать!
#     # jd1 НЕ ПОЯВИТСЯ в списке!
#     jd1:
#         name: J. Doe
#         fullName: John Doe
#         cabinet: 5c
# Тег external работает со всеми другими списками, даже так:
#
# teachers:
#     jd1:
#         external: teacher-jd1.yml

teachers:
    at1: [А. Т. Александровна, Антонова Татьяна Александровна, 6]
    tl1: [Т. Л. Дмитриевна, Точеная Любовь Дмитриевна, Каб. Директора]
    mm1: [М. М. Борисович, Моисеев Максим Борисович, 11]
    lt1: [Л. Т. Анатольевна, Лимонова Татьяна Анатольевна, 4]
    ga1: [Г. А. Владимировна, Гориченко Анна Владимировна, 7]
    vp1: [В. П. Владимировна, Волкова Полина Владимировна, Каб. Информатики]
    sa1: [С. А. Михайловна, Семёнова Александра Михайловна, .]
    kt1: [К. Т. Борисовна, Крета Татьяна Борисовна, .]
    pl1: [П. Л. Андреевна, Прециниек Людмила Андреевна, .]
    zd1: [З. Д. Александрович, Зинин Данил Александрович, .]


lessons:
    ru1-9a:
        teacher: at1
        name: Русский язык
        cabinet: 9

    en1-9a:
        teacher: tl1
        name: Английский язык
        cabinet: 9

    ph1-9a:
        teacher: mm1
        name: Физика
        cabinet: 9/11

    hi1-9a:
        teacher: lt2
        name: История
        cabinet: 9

    al1-9a:
        teacher: lt1
        name: Алгебра
        cabinet: 9

    ch1-9a:
        teacher: vp1
        name: Химия
        cabinet: 9

    bi1-9a:
        teacher: sa1
        name: Биология
        cabinet: 9

    ge1-9a:
        teacher: kt1
        name: География
        cabinet: 9

    ge2-9a:
        teacher: lt1
        name: Геометрия
        cabinet: 9

    rr1-9a:
        teacher: pl1
        name: Родная русская Литература
        cabinet: 9

    li1-9a:
        teacher: ta1
        name: Литература
        cabinet: 9

    rr2-9a:
        teacher: pl1
        name: Родной Русский Язык
        cabinet: 9

    pa1-9a:
        teacher: zd1
        name: Физкультура
        cabinet: Зал

    ob1-9a:
        teacher: kt1
        name: Обществознание
        cabinet: 9

    it1-9a:
        teacher: vp1
        name: Информатика
        cabinet: Каб. Информатики

    ob2-9a:
        teacher: sa1
        name: ОБЖ
        cabinet: 9

grades:
    9A:
        name: 9A
        cabinet: 9
        teacher: at1
        schedule: [
            [en1-9a, ru1-9a, ph1-9a, hi1-9a, al1-9a, ch1-9a, bi1-9a],
            [ge1-9a, ch1-9a, ge2-9a, ph1-9a, rr1-9a, bi1-9a, li1-9a],
            [ph1-9a, hi1-9a, li1-9a, rr1-9a, rr2-9a, en1-9a, pa1-9a],
            [pa1-9a, ob1-9a, ge1-9a, ru1-9a, li1-9a, ge2-9a],
            [it1-9a, en1-9a, ob2-9a, ru1-9a, ch1-9a, al1-9a]
        ]
